<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $employees = [
            [
                'employee_id' => 'EMP001',
                'name' => 'Ahmad Rizki Pratama',
                'email' => 'ahmad.rizki@company.com',
                'phone' => '08123456789',
                'address' => 'Jl. Sudirman No. 123, Jakarta',
                'hire_date' => '2024-01-01',
                'status' => 'active',
                'position' => 'Production Manager',
                'department' => 'Production',
                'location_id' => 1,
                'emergency_contact_name' => 'Siti Rizki',
                'emergency_contact_relation' => 'Istri',
                'emergency_contact_phone' => '08123456790',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_id' => 'EMP002',
                'name' => 'Sari Indah Permata',
                'email' => 'sari.indah@company.com',
                'phone' => '08234567890',
                'address' => 'Jl. Thamrin No. 456, Jakarta',
                'hire_date' => '2024-02-01',
                'status' => 'active',
                'position' => 'Quality Control Supervisor',
                'department' => 'Quality Assurance',
                'location_id' => 1,
                'emergency_contact_name' => 'Budi Santoso',
                'emergency_contact_relation' => 'Ayah',
                'emergency_contact_phone' => '08234567891',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_id' => 'EMP003',
                'name' => 'Dedi Kurniawan',
                'email' => 'dedi.kurniawan@company.com',
                'phone' => '08345678901',
                'address' => 'Jl. Gatot Subroto No. 789, Jakarta',
                'hire_date' => '2024-03-01',
                'status' => 'active',
                'position' => 'Production Operator',
                'department' => 'Production',
                'location_id' => 2,
                'emergency_contact_name' => 'Rina Kurniawan',
                'emergency_contact_relation' => 'Istri',
                'emergency_contact_phone' => '08345678902',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_id' => 'EMP004',
                'name' => 'Maya Sari Dewi',
                'email' => 'maya.sari@company.com',
                'phone' => '08456789012',
                'address' => 'Jl. Rasuna Said No. 321, Jakarta',
                'hire_date' => '2024-04-01',
                'status' => 'active',
                'position' => 'HR Specialist',
                'department' => 'Human Resources',
                'location_id' => 1,
                'emergency_contact_name' => 'Agus Dewi',
                'emergency_contact_relation' => 'Suami',
                'emergency_contact_phone' => '08456789013',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_id' => 'EMP005',
                'name' => 'Rudi Hartono',
                'email' => 'rudi.hartono@company.com',
                'phone' => '08567890123',
                'address' => 'Jl. Kuningan No. 654, Jakarta',
                'hire_date' => '2024-05-01',
                'status' => 'active',
                'position' => 'Warehouse Coordinator',
                'department' => 'Logistics',
                'location_id' => 2,
                'emergency_contact_name' => 'Indira Hartono',
                'emergency_contact_relation' => 'Anak',
                'emergency_contact_phone' => '08567890124',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_id' => 'EMP006',
                'name' => 'Lisa Kartika',
                'email' => 'lisa.kartika@company.com',
                'phone' => '08678901234',
                'address' => 'Jl. Senayan No. 987, Jakarta',
                'hire_date' => '2024-01-15',
                'status' => 'active',
                'position' => 'Production Operator',
                'department' => 'Production',
                'location_id' => 1,
                'emergency_contact_name' => 'Wawan Kartika',
                'emergency_contact_relation' => 'Kakak',
                'emergency_contact_phone' => '08678901235',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_id' => 'EMP007',
                'name' => 'Andi Setiawan',
                'email' => 'andi.setiawan@company.com',
                'phone' => '08789012345',
                'address' => 'Jl. Mangga Dua No. 159, Jakarta',
                'hire_date' => '2024-02-20',
                'status' => 'active',
                'position' => 'Maintenance Technician',
                'department' => 'Maintenance',
                'location_id' => 2,
                'emergency_contact_name' => 'Nurul Setiawan',
                'emergency_contact_relation' => 'Istri',
                'emergency_contact_phone' => '08789012346',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_id' => 'EMP008',
                'name' => 'Fitri Handayani',
                'email' => 'fitri.handayani@company.com',
                'phone' => '08890123456',
                'address' => 'Jl. Kemang No. 753, Jakarta',
                'hire_date' => '2024-03-10',
                'status' => 'inactive',
                'position' => 'Admin Assistant',
                'department' => 'Administration',
                'location_id' => 1,
                'emergency_contact_name' => 'Hendra Handayani',
                'emergency_contact_relation' => 'Ayah',
                'emergency_contact_phone' => '08890123457',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('employees')->insert($employees);
    }
}
